# Generated by Django 4.0.6 on 2022-08-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_feature_package"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="User id")),
                ("package_id", models.IntegerField(verbose_name="Package id")),
                (
                    "total_amount_paid",
                    models.IntegerField(verbose_name="Total Amount Paid"),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Subscription Start Date"),
                ),
                (
                    "expiry_date",
                    models.DateField(verbose_name="Subscription Expiry Date"),
                ),
                (
                    "email",
                    models.CharField(max_length=256, verbose_name="Client's Email"),
                ),
                (
                    "country_code",
                    models.CharField(max_length=9, verbose_name="Client's Country"),
                ),
                (
                    "address",
                    models.CharField(max_length=256, verbose_name="Client's Address"),
                ),
                (
                    "order_key",
                    models.CharField(max_length=256, verbose_name="Order key"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="pricing",
            name="name",
            field=models.CharField(max_length=256, verbose_name="Name"),
        ),
    ]
