# Generated by Django 4.0.6 on 2022-08-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0004_subscription_alter_pricing_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricing",
            name="annualy_price",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Annual Pricing"
            ),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="price",
            field=models.IntegerField(verbose_name="Monthly Pricing"),
        ),
    ]
