# Generated by Django 4.0.6 on 2022-08-02 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0005_pricing_annualy_price_alter_pricing_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name="Subscription Start Date",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="total_amount_paid",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Total Amount Paid"
            ),
        ),
    ]
