# Generated by Django 4.0.6 on 2022-08-02 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0006_alter_subscription_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="package_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="manager.package"
            ),
        ),
    ]
