# Generated by Django 4.0.6 on 2022-08-02 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_subscription_package_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pricing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.pricing'),
            preserve_default=False,
        ),
    ]
