# Generated by Django 4.0.6 on 2022-08-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_subscription_pricing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user_id',
            new_name='user',
        ),
    ]
