# Generated by Django 4.0.6 on 2022-08-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_subscription_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='expired',
            field=models.BooleanField(default=False, verbose_name='Expired'),
        ),
    ]
