# Generated by Django 4.0.6 on 2022-09-17 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_subscription_active_subscription_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_completed',
            field=models.BooleanField(default=False, verbose_name='Payment Completed'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='previous_pricing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_pricing', to='manager.pricing'),
        ),
    ]
