# Generated by Django 4.0.6 on 2022-09-17 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_subscription_payment_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='upgrading_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upgrading_to', to='manager.pricing'),
        ),
    ]
